# Generated by Django 2.0.3 on 2018-07-01 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('date', models.DateTimeField(verbose_name='Date time')),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='Notes')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Members name')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='Paid by')),
            ],
            options={
                'permissions': (('view_own_payment', 'Can view own payments'), ('view_all_payments', 'Can view all payments')),
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=150, unique=True, verbose_name='Payment type')),
                ('frequency', models.CharField(choices=[('UNSET', 'Unset'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='UNSET', max_length=100, verbose_name='Frequency')),
                ('min_amount', models.IntegerField(verbose_name='Minimum amount')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.CharField(default='<django.db.models.fields.charfield>', max_length=250)),
                ('flag', models.CharField(choices=[('saving_account', 'Saving account'), ('registration_fee', 'Registration Fees')], default='saving_account', max_length=150, verbose_name='Flag')),
            ],
            options={
                'permissions': (('view_payment_type', 'Can view payment types'),),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.PaymentType', verbose_name='Payment category'),
        ),
    ]
