# Generated by Django 2.0.3 on 2018-07-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=150)),
                ('tagline_left', models.CharField(max_length=150)),
                ('section1_title', models.CharField(max_length=150)),
                ('section1_text', models.TextField(verbose_name='Section1 text')),
                ('section2_title', models.CharField(max_length=150)),
                ('section2_text', models.TextField(verbose_name='Section2 text')),
                ('section3_title', models.CharField(max_length=150)),
                ('section3_text', models.TextField(verbose_name='Section3 text')),
                ('section4_title', models.CharField(max_length=150)),
                ('section4_text', models.TextField(verbose_name='Section4 text')),
                ('section5_title', models.CharField(max_length=150)),
                ('section5_text', models.TextField(verbose_name='Section5 text')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='downloads')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField(max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('facebook_url', models.URLField(max_length=500)),
                ('googleplus_url', models.URLField(max_length=500)),
                ('twitter_url', models.URLField(max_length=500)),
                ('linked_in_url', models.URLField(max_length=500)),
                ('dribble_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FooterRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=100)),
                ('signup_link_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FunActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_top', models.CharField(max_length=150)),
                ('title_bottom', models.CharField(max_length=150)),
                ('keyword1', models.CharField(max_length=150)),
                ('keyword2', models.CharField(max_length=150)),
                ('keyword3', models.CharField(max_length=150)),
                ('form_title', models.CharField(max_length=150)),
                ('background_image', models.ImageField(upload_to='background_images')),
            ],
            options={
                'permissions': (('can_update_website', 'Can update website'),),
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='management_team')),
                ('caption', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('section', models.CharField(choices=[('management', 'Management'), ('supervisory', 'Supervisory committee'), ('activities', 'Activities'), ('projects', 'Projects')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisoryCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=150)),
            ],
        ),
    ]
