# Generated by Django 2.0.3 on 2018-07-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField(default=0.0, verbose_name='credit')),
                ('debit', models.FloatField(default=0.0, verbose_name='debit')),
                ('amount_outstanding', models.FloatField(default=0.0, verbose_name='Amount outstanding')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
