# Generated by Django 2.0.3 on 2018-07-01 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='member_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
