# Generated by Django 2.0.3 on 2018-07-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DividendDisbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('view_dividend_disbursements', 'Can see dividend disbursements'),),
            },
        ),
        migrations.CreateModel(
            name='DividendIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=500, verbose_name='Issue for the period')),
                ('date_effective', models.DateTimeField(help_text='Members balance as at this date is used to calculate dividends.', verbose_name='Date effective.')),
                ('percentage', models.FloatField(default=5.0, max_length=50)),
                ('notes', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'permissions': (('view_dividend_issues', 'Can see available issues'),),
            },
        ),
        migrations.AddField(
            model_name='dividenddisbursement',
            name='dividend_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dividends.DividendIssue', verbose_name='Dividend Issue'),
        ),
    ]
