# Generated by Django 2.0.3 on 2018-07-01 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField(max_length=50)),
                ('debit', models.FloatField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('module', models.CharField(choices=[('Shares', 'shares'), ('Contributions', 'contributions'), ('Loans', 'loans'), ('Fines', 'fines')], max_length=100)),
                ('staff', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=250)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
