# Generated by Django 2.0.3 on 2018-07-01 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_disbursed', models.FloatField(verbose_name='Amount disbursed')),
                ('repayment_period_unit', models.CharField(choices=[('months', 'Months'), ('years', 'Years'), ('weeks', 'Weeks'), ('days', 'Days')], default='months', max_length=50, verbose_name='Repayment period unit')),
                ('interest_rate', models.FloatField(default=12.0, max_length=50, verbose_name='Interest rate (p.a.)')),
                ('interest_on', models.CharField(choices=[('reducing_balance', 'Reducing balance'), ('flat_rate', 'Flat rate')], default='reducing_balance', max_length=50, verbose_name='Calculate interest on')),
                ('repayment_period', models.IntegerField(blank=True, default=24, help_text='Enter repayment period for this type of loan', verbose_name='Repayment period')),
                ('processing_fee', models.FloatField(null=True, verbose_name='Processing fee')),
                ('date_disbursed', models.DateTimeField(auto_now_add=True, verbose_name='Date disbursed')),
                ('first_due', models.DateField(default=datetime.datetime(2018, 8, 15, 18, 0, 15, 234879), verbose_name='Date due')),
                ('next_due', models.DateField(blank=True, verbose_name='Next due')),
            ],
            options={
                'permissions': (('disburse_loan', 'Can make loan disbursements'), ('view_loan_disbursements', 'Can see loan disbursements')),
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Rejected', 'rejected')], default='pending', max_length=50, verbose_name='Status')),
                ('response_message', models.TextField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('min_amount', models.FloatField(verbose_name='Minimum amount')),
                ('max_amount', models.FloatField(verbose_name='Maximum amount')),
                ('repayment_period', models.IntegerField(blank=True, help_text='Enter repayment period for this type of loan', verbose_name='Repayment period')),
                ('repayment_period_unit', models.CharField(choices=[('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='MONTHS', max_length=50, verbose_name='Repayment period unit')),
                ('interest_rate', models.FloatField(default=12.0, max_length=50, verbose_name='Interest rate (p.a.)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'permissions': (('view_loans', 'Can see loans'), ('request_loan', 'Can request loan')),
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, max_length=100, verbose_name='Payment date')),
                ('next_due', models.DateTimeField(max_length=100, null=True, verbose_name='Next due')),
                ('credit', models.FloatField(default=0.0, verbose_name='Credit')),
                ('debit', models.FloatField(default=0.0, verbose_name='Debit')),
                ('total_paid', models.FloatField(verbose_name='Total paid')),
                ('outstanding', models.FloatField(max_length=50, verbose_name='Outstanding')),
                ('interest_epoch', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, default='', max_length=150)),
                ('principal', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'permissions': (('can_repay_loans', 'Can make loan repayment'), ('can_disburse_loans', 'Can disburse loans'), ('view_loan_repayments', 'Can see loan repayments')),
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.FloatField(verbose_name='Amount requested')),
                ('date_requested', models.DateTimeField(auto_now_add=True, verbose_name='Date requested')),
                ('details', models.TextField(blank=True, help_text='Provide any additional information here', verbose_name='More details')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approve'), ('rejected', 'Reject')], default='pending', max_length=100)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.Loan', verbose_name='Loan type')),
            ],
            options={
                'permissions': (('can_manage_loans', 'Can manage loans'), ('view_requests', 'Can see requests')),
            },
        ),
    ]
