# Generated by Django 2.0.3 on 2018-07-01 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Requesting member'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='loan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.LoanRequest', verbose_name='Loan request'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='guarantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='loan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.LoanRequest'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='loan_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans.LoanRequest', verbose_name='Loan request'),
        ),
    ]
