# Generated by Django 4.1.1 on 2023-01-31 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20180701_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='first_due',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 18, 32, 29, 213868), verbose_name='Date due'),
        ),
    ]
