# Generated by Django 2.0.3 on 2018-07-01 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(default=649, unique=True)),
                ('account_name', models.CharField(max_length=250)),
                ('inherits', models.CharField(default='none', max_length=250)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('expense', 'Expense'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('other_account', 'Other Account')], default='liability', max_length=250)),
                ('increases', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=250)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=250)),
                ('opening_balance', models.FloatField(default=0.0)),
                ('opening_date', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(unique=True)),
                ('group_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('amount', models.FloatField(default=0.0)),
                ('narration', models.TextField(max_length=500)),
                ('member', models.CharField(default='none', max_length=250)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
        migrations.CreateModel(
            name='BuiltInAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=250)),
                ('slug', models.CharField(default='<django.db.models.fields.charfield>', max_length=250, unique=True)),
            ],
        ),
    ]
